/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libreria;
import java.io.File;

/** Frame per aggiungere un elemento alla libreria.
 * 
 * Questa classe implementa un frame per l'inserimento dei dati necessari
 * all'inserimento dei dati da parte dell'utente.
 *
 * @author Marco
 */
public class AggiungiFrame extends javax.swing.JFrame {
    private int tipo;
    private Elemento temp = null;
    private File f;
    private MyLibreria lib;
    private MyTableModel modello;
    /**
     * Creates new form .
     * 
     * @param tipo identifica il tipo di elemento in modo da adattare l'interfaccia.
     * @param lib riferimento alla libreria nella quale inserire l'elemento.
     */
    public AggiungiFrame(int tipo, MyLibreria lib, MyTableModel modello) {
        this.modello=modello;
        this.tipo=tipo;
        this.lib=lib;
        initComponents();
        switch (tipo){
            case 1: jLabelA.setText("Durata"); break;
            case 2: jLabelA.setText("Durata"); break;
            case 3: jLabelA.setText("N Pagine"); break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTextAutore = new javax.swing.JTextField();
        JTextTitolo = new javax.swing.JTextField();
        JTextPercorso = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        JTextAnno = new javax.swing.JTextField();
        jLabelAnno = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabelA = new javax.swing.JLabel();
        JTextA = new javax.swing.JTextField();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserimento elemento");

        jLabel1.setText("Titolo");

        jLabel2.setText("Autore");

        jLabel3.setText("File ");

        JTextPercorso.setEditable(false);

        jButton1.setText("Sfoglia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelAnno.setText("Anno");

        jButton2.setText("OK");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelA.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabelAnno)
                                    .addComponent(jLabelA))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTextA, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTextTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTextAutore, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JTextPercorso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))
                                    .addComponent(JTextAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 108, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTextTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTextAutore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTextPercorso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAnno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelA)
                    .addComponent(JTextA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Azioni bottone Sfoglia.
     * 
     * Implementa l'apertura del file chooser e setta il percorso
     * 
     * @param evt identifica l'evento che ha generato la chiamata.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MyFileChooser fc = new MyFileChooser(tipo);
        f = fc.getFile();
        if (f!=null){
            JTextPercorso.setText(""+f.getName());
            jButton2.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
/** Azioni bottone ok.
 * 
 * Inserisce l'elemento creato dall'utente nella libreria.
 * 
 * @param evt identifica l'evento
 */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
 
            switch (tipo){
                case 1: lib.creaBrano(JTextTitolo.getText(), JTextAutore.getText(), JTextAnno.getText(), JTextA.getText(), "60",f.getAbsolutePath()); break;
                case 2: lib.creaVideo(JTextTitolo.getText(), JTextAutore.getText(), JTextAnno.getText(), JTextA.getText(), f.getAbsolutePath()); break;
                case 3: lib.creaEBook(JTextTitolo.getText(), JTextAutore.getText(), JTextAnno.getText(), JTextA.getText(), f.getAbsolutePath() ); break;
            }
            
            //AGGIORNAMENTO
            modello.aggiorna();
        
        this.dispose();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextA;
    private javax.swing.JTextField JTextAnno;
    private javax.swing.JTextField JTextAutore;
    private javax.swing.JTextField JTextPercorso;
    private javax.swing.JTextField JTextTitolo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelA;
    private javax.swing.JLabel jLabelAnno;
    // End of variables declaration//GEN-END:variables
}
